services:
  postgres:
    build:
      context: .
      dockerfile: docker/postgres.Dockerfile
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - 'postgres-data-vol:/var/lib/postgresql/data:Z'
    restart: on-failure
volumes:
  postgres-data-vol:
